# Generated by ariadne-codegen
# Source: https://api.github.com/graphql

from enum import Enum

class StatusState(str, Enum):
    EXPECTED = "EXPECTED"
    ERROR = "ERROR"
    FAILURE = "FAILURE"
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"

class IssueState(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"

class IssueStateReason(str, Enum):
    REOPENED = "REOPENED"
    NOT_PLANNED = "NOT_PLANNED"
    COMPLETED = "COMPLETED"
    DUPLICATE = "DUPLICATE"

class PullRequestState(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    MERGED = "MERGED"
